### PR TITLE
Menu Title

### PR DESCRIPTION
**Pull request by zachpainter77**
proposed change allows for user to set "isMenuTitle" boolean if true then creates a span instead of styled anchor element...

### CODE REVIEW

**Comment by mar10** [comment]
Thanks for contributing. How would this work with jQuery UI 1.11+ ?

**Comment by zachpainter77** [comment]
I don't think there would be any issues with 1.11

**Comment by mar10** [comment]
Did you try it? I guess you proposed this fix, in order to make these entries appear as non-clickable headers, by removing the `<a>` tags.
But jQuery UI Menu 1.11 does not require `<a>`tags at all.

**Comment by zachpainter77** [comment]
Ok I guess I didn't try that.. Are you planning on changing the code to use
jquery ui 1.11? You can implement the new version support and I can rewrite
the menu title again to fit I guess..

**Comment by zachpainter77** [comment]
I see jquery ui menu just creates ul with each menu item a li element... So
I would need to change my proposed changes to fit that..

**Comment by mar10** [comment]
> Are you planning on changing the code to use
jquery ui 1.11? You can implement the new version support and I can rewrite
the menu title again to fit I guess..

It is already implemented, about 10 lines below your change

**Comment by zachpainter77** [comment]
Ahh Ok then I'll update the proposed change then to support that..

**Comment by zachpainter77** [comment]
Ok support for 1.11+ has been added

**Comment by zachpainter77** [comment]
It appears that I'm not to use single quotes for strings... but I don't know how to resolve this conflict... :/

**Comment by mar10** [comment]
This pull request introduces inline CSS to style the 'title' entries.
A more elegant and flexible way would be to use classes.
But then: this is already available by the `addClass` option. Combined with the `disabled` option it should be possible to achieve the desired effect(?)

**Pull request closed without merging**
